# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-16 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_path', models.TextField()),
                ('csv_path', models.TextField()),
            ],
        ),
    ]
