# Generated by Django 2.2.6 on 2019-11-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyprediction',
            name='csv_path',
        ),
        migrations.RemoveField(
            model_name='energyprediction',
            name='sql_path',
        ),
        migrations.AddField(
            model_name='energyprediction',
            name='electricity_facility',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
